jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B
  integrations:
    name: Integration test (Boot ${{ matrix.boot-version }})
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Maven (Boot ${{ matrix.boot-version }})
      run: sed -i -e 's/2.7.1/${{ matrix.boot-version }}/g' ./pom.xml && ./mvnw dependency:list
        -B && ./mvnw -B
    strategy:
      matrix:
        boot-version:
        - 2.5.14
        - 2.6.9
        - 3.0.0-SNAPSHOT
name: Maven Build
on:
  repository_dispatch:
    types: trigger-ga___build.yaml
